workflows:
  android-build:
    name: KeepFlow Notes Pro
    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Start
        script: echo "Build starting..."

      - name: Grant permission
        script: chmod +x gradlew

      - name: Setup local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
