workflows:
  keepflow-notes-pro:
    name: KeepFlow Notes Pro

    max_build_duration: 60

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - chmod +x gradlew
      - echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - ./gradlew clean
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
